### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by rafaelklaessen** [WouterMolhoek/Google-Keep#9]
With 
`ref.push({
    title: "title",
    description: '<marquee><h1 style="font-size: 50px; color: green">XSS</h1></marquee>',
    color: "#FF00FF"
  });` 
from the browser console, everyone can send HTML into your application. You can fix this by escaping the content/title from Firebase before rendering the DOM.

**Comment by WouterMolhoek** [comment]
Bug is fixed, changed innerHTML to innerText.

**Comment by rafaelklaessen** [comment]
When you fix an issue in a commit, name it `fixed #9 Removed XSS`. Adding `fixed #issueId` will automatically close the issue.

**Comment by rafaelklaessen** [comment]
@WouterMolhoek Have you read this?
